name: Build and Release

on:
  push:

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        # Include amd64 on all platforms.
        goos: [windows, freebsd, openbsd, linux, darwin]
        goarch: [amd64, 386]
        exclude:
          # Exclude i386 on darwin
          - goarch: 386
            goos: darwin
        include:
          # BEIGIN MacOS ARM64
          - goos: darwin
            goarch: arm64
          # END MacOS ARM64
          # BEGIN Linux ARM 5 6 7
          - goos: linux
            goarch: arm
            goarm: 7
          # END Linux ARM 5 6 7
          # BEGIN Android ARM 8
          - goos: android
            goarch: arm64
          # END Android ARM 8
      fail-fast: false

    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOARM: ${{ matrix.goarm }}
      CGO_ENABLED: 0
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Show workflow information 
        run: |
          export _NAME=$(jq ".[\"$GOOS-$GOARCH$GOARM$GOMIPS\"].friendlyName" -r < .github/build/friendly-filenames.json)
          echo "GOOS: $GOOS, GOARCH: $GOARCH, GOARM: $GOARM, GOMIPS: $GOMIPS, RELEASE_NAME: $_NAME"
          echo "ASSET_NAME=$_NAME" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true

      - name: Get project dependencies
        run: go mod download && go mod tidy
 
      - name: Build cfipscanner
        run: |
          mkdir -p build_assets
          go build -v -o build_assets/cfipscanner -trimpath -ldflags "-s -w -buildid=" ./main

      - name: Build background cfipscanner on Windows 
        if: matrix.goos == 'windows'
        run: |
          go build -v -o build_assets/cfipscanner.exe -trimpath -ldflags "-s -w -H windowsgui -buildid=" ./main
    
      - name: Build Mips softfloat cfipscanner
        if: matrix.goarch == 'mips' || matrix.goarch == 'mipsle'
        run: |
          GOMIPS=softfloat go build -v -o build_assets/cfipscanner_softfloat -trimpath -ldflags "-s -w -buildid=" ./main


      - name: Create ZIP archive
        shell: bash
        run: |
          pushd build_assets || exit 1
          touch -mt $(date +%Y01010000) *
          zip -9vr ../cfipscanner-${{matrix.goos}}-${{matrix.goarch}}.zip .
          popd || exit 1
          FILE=./cfipscanner-${{matrix.goos}}-${{matrix.goarch}}.zip
          DGST=$FILE.dgst
          for METHOD in {"md5","sha1","sha256","sha512"}
          do
            openssl dgst -$METHOD $FILE | sed 's/([^)]*)//g' >>$DGST
          done

      - name: Change the name
        run: |
          mv build_assets cfipscanner-${{matrix.goos}}-${{matrix.goarch}}

      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cfipscanner-${{matrix.goos}}-${{matrix.goarch}}
          path: |
            ./cfipscanner-${{matrix.goos}}-${{matrix.goarch}}/*

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: contains(github.ref, 'release')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./cfipscanner-${{matrix.goos}}-${{matrix.goarch}}.zip*
          tag: ${{ github.ref }}
          file_glob: true
